### PR TITLE
Issue #2587: Compress JPEGs more

### PR DESCRIPTION
**Pull request by AnneTee**
This came up because our site is getting a nasty red exclamation point for optimizing images on [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=savaslabs.com). I looked into it and the JPEG optimizer used by `imagemin` by default is lossless, so if we want more compression we need to use a lossy one. I subbed in the `imagemin-jpeg-recompress` plugin and did a lot of manual compression of the offending JPEGs - case study hero images.

To test, pull this branch and run `gulp serve`. Once the site is up, compare some of the case study hero images to those on the live site - you shouldn't really be able to tell a difference. You can also look at the generated `assets/img` directory (no underscore before "assets") - the size should drop from ~27MB to ~21MB.

Another way to test would be to run `./ngrok http 3000` wherever you have `ngrok` installed, then paste the ngrok URL into PageSpeed Insights. Better yet, paste the ngrok URL + /work to test all the hero images. Note that you will see suggestions to enable compression and minify HTML - these are taken care of by GitHub Pages on the live site, so we don't need to worry about them locally.

### CODE REVIEW

**Comment by lrowang** [comment]
Hi @AnneTee - 

Gulp can't seem to find `imagemin-jpeg-recompress` when I run `gulp serve`. This happens regardless if I'm in a `HEAD` state or if I've checkout out a local branch tracking yours. 

I see that `imagemin-jpeg-recompress` is being specified in `package.json`, but is there something else I have to do (like a quick "update/provision") to install it? Or do I have to go through the entire `npm install` again?

gulperror

**Comment by AnneTee** [comment]
@lrowang Ahhh! Sorry, I left that step out. I'm pretty sure `npm install` will just install the node modules you're missing, so, the one you need to get this to work. It should only install all of them if you delete everything in `node_modules`.

**Comment by lrowang** [comment]
Hi @AnneTee -

This is cool! As you said, I couldn't tell by visual comparison, but `assets` is smaller and when I compared the `/work` pages with `ngrok` there was a clear score difference! 

Notes/questions:
- I added a line about `npm install` to the README "Local Development" section if that's okay! (In general, do we prefer to have a separate PR for that kind of thing or okay here?)
- Why did you have to manually compress the case study hero images? I would have thought the plugin `imagemin-jpeg-recompress` takes care of that and that's why we subbed it in?
- Also thank you for sharing `ngrok`-- so cool! 👍 👍

**Comment by AnneTee** [comment]
@lrowang Thanks for updating the README, good call!

I'll probably need to play around with the options for `jpegoptim` so we don't have to manually compress images in the future - I'm betting it can be set to destroy unneeded data in the image less conservatively than the default. For the time being, especially since the only images causing issues were the hero images which I could easily export at a lower quality then compress using a simple program, it seems to be compressing things enough now.

**Pull request merged**
