### PR TITLE
[WIP] Feature/welcome ben

### PR DESCRIPTION
**Pull request by chrisarusso**
Check it

## Summary of changes

1. Adds a blog post welcoming Ben. [Here's the staged version](https://stage3--savas-staging.netlify.com/2018/12/10/savas-welcomes-ben-eckerson-coo.html)

## Notes

See `TODO`s embedded in the file

@AnneTee 

- [ ] Verify the update to the SCSS file is legitimate. This is unrelated to this post, but figured I'd squeeze it in. On Desktop width and above there's no right padding in the social links in the footer and it seems there should be so they're not right up against the edge of the screen.
- [ ] Please add styles to make the centering and padding for Instagram and LinkedIn embeds match the Twitter one. 

@beneckerson 

Have a look see and let's discuss your feedback on content and tagging

### CODE REVIEW

**Comment by beneckerson** [comment]
I need a proper tutorial on how to make changes in red and green in github line by line in the markdown file (which may require me pulling this down locally maybe?) but in the meantime here are my suggested edits:

- [x] Change out the photo of me as a child with the headshot that's on the site 
- [x] Change sentence / paragraph to 
> Ben joins us after six years at premier digital agency Viget, where he led business development and experimental IoT efforts for their Durham office (a couple blocks away from us in downtown Durham). 
- [x] Link "McKinney" to http://mckinney.com
- [x] Sub stick stickly photo for my kindergarten photo used in the header 
- [x] Change sentence / paragraph to 
> With well over a decade in leadership roles in digital agencies, Ben will help to improve our operations to enhance the value we're providing to our partners. He'll also help get the exemplary work we do here at Savas out in the world better. Known for his knack for turning creative visions into reality, Ben will be the first person a new organization has a conversation with about how we can help them achieve their hopes and dreams or the first phone chat of a prospective job candidate [link to careers]. Beyond his official duties, Ben is a high-energy, team player who seeks to foster a fun and healthy culture with his new work family and we’re seeing that impact already.
- [x] Change sentence / paragraph / order to 
> * We've transitioned our internal team planning / scheduling efforts into Harvest's forecast [link]
> * We've improved our retrospective process / documentation as well as our organization of project files in our Google Drive 
> * We’ve had to up our Slack subscription :slack: to keep pace with Ben’s uncanny ability to find the perfect GIF (or create a new custom emoji) for any conversation.
> * We've implemented an inaugural Secret Santa [office link] tradition in the office
> * We've instituted (and started planning) semi-annual retreats to bring together the full distributed team. Spring 2019 is in the planning stages:
- [x] See if you can center the linkedin embed (it seems like it's left aligned versus the Twitter embed)
- [x] Can we do photo captions? If so I'd suggest one for my kindergarten photo (which would now be where stick stickly is) that would say _Ben dove right in sharing this kindergarten school photo with the team_ then one for the google maps that says _One of Ben's nominations for our retreat is Paris (Illinois)_

**Comment by beneckerson** [comment]
Suggested Tags:

Identity
Team
Company Culture

**Comment by chrisarusso** [comment]
Checking off updates made per push just now

**Comment by beneckerson** [comment]
These last three bullets (the copy) wasn't properly tweaked, should read:

- We’ve had to up our Slack subscription :slack: to keep pace with Ben’s uncanny ability to find the perfect GIF (or create a new custom emoji) for any conversation.
- We've implemented an inaugural Secret Santa [office link] tradition in the office
- We've instituted (and started planning) semi-annual retreats to bring together the full distributed team. Spring 2019 is in the planning stages:

cc: @chrisarusso

**Comment by beneckerson** [comment]
crop-centralpoint
Photo replacement for the one we chatted about

**Comment by beneckerson** [comment]
ben-landscape

Landscape photo @chrisarusso

**Pull request closed without merging**
