### PR TITLE
[WIP] Feature #43: comment form

### PR DESCRIPTION
**Pull request by AnneTee**
To do:
- use ajax to append new comment
- make sure timezone is correct

### CODE REVIEW

**Comment by AnneTee** [comment]
@kostajh I just pushed up a WIP commit to append the new comment to the page using Ajax. I left you some comments in the code. :octocat:

**Comment by kostajh** [comment]
cool! We also need to add the "nocaptcha" field.

**Comment by kostajh** [comment]
@AnneTee a few more things and I think this is good to go!
- [x] Place comment form below comments
- [x] Add a "Add a new comment" link after you click the "Comments!" expander
- [ ] Style comments left with @savaslabs.com email addresses so they stand out from regular ppl

**Comment by kostajh** [comment]
> First!
> :speech_balloon:

**Pull request merged**
