### PR TITLE
[WIP] SAV-29 blog

### PR DESCRIPTION
**Pull request by kostajh**
Opening a PR for review

### CODE REVIEW

**Comment by kostajh** [comment]
@AnneTee in general, I think this is good to merge as is after we prune the veggie posts. 

In my blog posts I usually like to include code blocks. Pretty code blocks are important to me. e.g.

```php
$doesnt_this_look = 'nice?';
class yes_it_does() extends Truth {
   __construct() {
     return true;
  }
}
```

So we should figure out how to incorporate that into the `_config.yml`. Adding `highlighter: pygments` to the `_config.yml` gets us part of the way but we should add some pretty syntaxt highlighting CSS. I'm partial to [Solarized](http://ethanschoonover.com/solarized) but am open to suggestions.

What else do you think needs to be done to take this live?

**Comment by kostajh** [comment]
Also, for some reason, code like this (https://gist.github.com/kostajh/f4ba67be047ec3663e0f) doesn't render properly. But using this syntax works:

```
{% highlight php linenos %}
<?php
$int = 5;
$string = "hello";
test($string, $int);
class Blah extends something {
public function blah() {

}
}
{% endhighlight %}
```

My understanding is that both should work, and obviously the first one is a lot easier to type than the latter, but not a big deal if we can't get that working.

**Comment by kostajh** [comment]
Another issue. on `/blog` the menu at the top only shows `Recent blog posts`, so you can't easily get back to the rest of the site.

**Comment by AnneTee** [comment]
@kostajh, a good point (and a very nice example) about code highlighting being a priority. I'll look into it.

For the menu, the SAVAS logo is a link to home (this might be too unclear), but I wasn't sure what else should include in the nav on /blog and posts pages. We could just keep the same nav as the main page, but it might be a little awkward since those links go to sections on the main page and not distinct pages. I'm not sure which route is better. Thoughts?

**Comment by AnneTee** [comment]
@kostajh As far as what else it needs, I'd really like to set up a header. @timstallmann has a good track record for figuring out headers so maybe he will have some ideas when he returns next week.

**Pull request closed without merging**
