### PR TITLE
Issue #3336: Update related posts logic

### PR DESCRIPTION
**Pull request by AnneTee**
@oksana-c This resolves the related posts issue, updating the logic so the current post won't show.

cc @chrisarusso thanks for catching!

### CODE REVIEW

**Comment by oksana-c** [comment]
Same post does not appear in the "Related posts" block, but now I see same post appearing twice within Related posts. Attaching screenshot and will dig into this tomorrow.

screen shot 2017-04-19 at 7 18 43 pm

**Review by oksana-c — CHANGES_REQUESTED** [review]
needs work

**Comment by AnneTee** [comment]
@oksana-c Sorry about that; I removed some logic from the template that I shouldn't have. This should be fixed now!

**Comment by oksana-c** [comment]
morning @AnneTee. Thanks for the quick update. I left a comment in Redmine task #3336. Merging.

**Review by oksana-c — APPROVED** [review]

**Pull request merged**
