### PR TITLE
[Merge with caution/a few free hours ahead of you] Issue #1297: Add gulp and optimize assets

### PR DESCRIPTION
**Pull request by AnneTee**
This PR includes:
- The addition of gulp to our site's build/serve processes (#2136)
- Minifying CSS and concatenating/uglifying JS (#1649)
- Optimizing current images (#1648)
- Optimizing images via gulp (#1647)
## To test

Follow the instructions in the README to install node modules and serve the site using gulp. Try running the test script, too.
## To note

The `assets` directory was moved to `_assets`. When building the site, gulp creates a git-ignored directory called `assets` with the generated files. This is so when gulp watch detects a change to a non-asset file (HTML, markdown, yml, etc.) and the `jekyll build` process is run, jekyll will copy the `assets` directory. If we weren't doing this, `jekyll build`, which wipes the `_site` directory, would delete all the asset files and not regenerate them.
## Further things we could do when we have the time
- Allow devs to add a `--drafts` tag to the `gulp serve` command to publish drafts
- Place scripts at the end of the HTML body
- Inline critical CSS

### CODE REVIEW

**Comment by AnneTee** [comment]
Looks like I need to tell travis to install node modules

**Comment by timstallmann** [comment]
This is working locally and the gulp file looks good to me! Thx for the very helpful readme also!

The only issue I notice is that `gulp-minify-css` is deprecated in favor of https://github.com/scniro/gulp-clean-css

**Comment by AnneTee** [comment]
@timstallmann Yay!!! Thanks for the tip, I'll make that update

**Comment by AnneTee** [comment]
I just merged in [this PR](https://github.com/AnneTee/savaslabs.github.io/pull/1) that covers image optimization. I wanted to make it a little easier to review that portion of the work since the diff in this PR is too big.

**Comment by AnneTee** [comment]
Looks like`jekyll_picture_tag` creates image paths that include the `site.url` found in `_config.yml`. This is probably not ideal, and it certainly messes up the HTMLproofer test (since it's looking for images on the production site instead of in the Travis environment).

**Comment by kostajh** [comment]
@AnneTee could I suggest `bundle install --path vendor/bundle` instead of `bundle install`? The latter prompted me to use `sudo` to install gems into my system ruby which I don't really want to do. Of course there's always :whale:

**Comment by AnneTee** [comment]
@timstallmann Woohoo, tests are passing now! You should be able to pull, run `npm install`, run `bundle install`, then `gulp serve`. It'll take a bit more time this time since images have to be processed (I have an issue open to cache these so it doesn't have to be done each time), but the site should look normal.

To test the picture tag, inspect team photos, blog post featured images (that are actually captured as featured images in front matter, not manually entered via markdown), or case study body images (not hero images). You should see the `<picture>` markup, and you should get the correct image size and resolution depending on your screen size and screen resolution. Images should have a natural size of twice their display dimensions on your retina screen. If you resize your screen, you should be served a different-sized image. You can check out `_config.yml` to see which image sizes to expect.

Example on Retina screen:
screen shot 2016-09-06 at 2 39 16 pm

Non-retina screen:
screen shot 2016-09-06 at 2 39 36 pm

You can also test the home page cover image - this is done via CSS media queries, not the `<picture>` element, but you should see different images depending on screen size and screen resolution.

Let me know if you run into any issues or have any suggestions. Thanks!

**Comment by timstallmann** [comment]
@AnneTee I had to install `imagemagick` locally via homebrew to get this to work. The error message is very non-descript `Liquid Exception: No such file or directory - identify in _layouts/team.html`. Could you add a note to the installation docs about installing `imagemagick`? And maybe some documentation about how to properly add image assets to a blog post so that they will be processed correctly?

Otherwise looks amazing. Great work!!! :stars: :pineapple:

**Comment by AnneTee** [comment]
@timstallmann Nice, thanks for pointing that out about ImageMagick - @kostajh I wonder if that's what is causing your issue. I'll add a note to the README. There are instructions in the README about adding blog images, but let me know if you think there needs to be more information there. Thanks for reviewing this!!

The gulp error messages are awful...I think on HPTN I used gulp-plumber to output more informative ones? I'll have to look into that.

**Comment by AnneTee** [comment]
Note: this was reverted via a force push since I couldn't get travis to run `gulp` to build the site on deploy.

**Pull request merged**
