### PR TITLE
Remove site.baseurl variable

### PR DESCRIPTION
**Pull request by kostajh**
This PR removes the site.baseurl variable. See commit message for more info.

### CODE REVIEW

**Comment by chrisarusso** [comment]
Not super savvy in this syntax nor the effects of these changes. I'm also not sure we want to modify feed.xml, because that's part of the initial commit, but for it if you think it's fine. Other than that, nothing  :smiling_imp:

**Comment by timstallmann** [comment]
@kostajh I feel like maybe that `baseurl` parameter was necessary for using this repo as a base for doing development on subsites like `/restaurant_map`? But I'm looking into it and I can't figure out how, so I feel fine with us removing it for now and if it causes problems later we'll know why.

**Comment by kostajh** [comment]
@timstallmann good point, but I think it will be fine. Looking at https://github.com/savaslabs/durham-restaurants-map/blob/master/_includes/head.html, it's using links like `<link rel="stylesheet" href="{{ "/assets/styles/main.css" | prepend: site.savas_baseurl }}">` which would translate to `http://savaslabs.com/assets/styles/main.css`

**Comment by kostajh** [comment]
@AnneTee what say you? shall we merge?

**Comment by AnneTee** [comment]
@kostajh I say yey

**Pull request merged**
