### PR TITLE
Feature/add durham

### PR DESCRIPTION
**Pull request by chrisarusso**
Fixes issue (Ben doesn't use issues yet)

## Summary of changes

1. Adds a /durham page featuring the #moffice

## Notes

This was primarily borrowed from our `/services` page and repurposed 

@AnneTee you should change things as you see fit. Considerations:

- I repurposed the client quote component for the TriDUG callout - but clearly it has nothing to do with a quote so changing the markup or used styles there is welcome.
- I created a `_durham.scss` file, but may not be the way it should be structured

## To test

- @AnneTee : See if you would make changes to structure
- @beneckerson : Verify it on the [staging site](https://savas-staging.netlify.com/durham/)

### CODE REVIEW

**Comment by beneckerson** [comment]
> Drupal User Group / Meetup
Should link to https://www.meetup.com/triDUG/

screen shot 2018-12-07 at 10 49 17 am

**Comment by beneckerson** [comment]
I used improper grammar per: https://www.myenglishteacher.eu/blog/whos-or-whose/

The first "Strategy / Consulting" should be 

**who's** and not **whose**

**Comment by beneckerson** [comment]
Other that those two things we are 👍 to go

**Comment by AnneTee** [comment]
Nice, I'll take a look at this this afternoon!

**Comment by chrisarusso** [comment]
Per that page, the HTML it expects in the `<head>` tag to achieve that is:

```
<!-- HTML Meta Tags -->
<title>Durham | Savas Labs</title>
<meta name="description" content="Savas Labs is a full-service digital agency leveraging the power of Drupal.">

<!-- Google / Search Engine Tags -->
<meta itemprop="name" content="Durham | Savas Labs">
<meta itemprop="description" content="Savas Labs is a full-service digital agency leveraging the power of Drupal.">
<meta itemprop="image" content="https://savas-staging.netlify.com/assets/img/bg/durham-deck.jpg">

<!-- Facebook Meta Tags -->
<meta property="og:url" content="https://savas-staging.netlify.com/durham">
<meta property="og:type" content="website">
<meta property="og:title" content="Durham | Savas Labs">
<meta property="og:description" content="Savas Labs is a full-service digital agency leveraging the power of Drupal.">
<meta property="og:image" content="https://savas-staging.netlify.com/assets/img/bg/durham-deck.jpg">

<!-- Twitter Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Durham | Savas Labs">
<meta name="twitter:description" content="Savas Labs is a full-service digital agency leveraging the power of Drupal.">
<meta name="twitter:image" content="https://savas-staging.netlify.com/assets/img/bg/durham-deck.jpg">

```

Maybe those should be new front matter default variables that get populated into `head.html`? This might spin off into its own task

**Comment by AnneTee** [comment]
Hey @chrisarusso and @beneckerson, I pushed a couple commits to:

- Use a banner template for the TriDug banner instead of the client quote template
- Add styles for this
- Reduce the size of the hero image (I resized it to twice its max size on the site, saved it at 90% quality, then ran it through tinyjpg)
- Change the background position of the hero image on small screens to it shows more of the deck

I agree that we should open a task for adding OG and meta tags!

**Comment by chrisarusso** [comment]
Thanks @AnneTee - I'll create the new issue around meta tags.

**Pull request merged**
