### PR TITLE
[WIP] Issue #717: update portfolio

### PR DESCRIPTION
**Pull request by AnneTee**
@chrisarusso So far I've created a case study that can act as a template for the rest for the Cognet responsive redesign (which I view as being separate from the other Cognet work we've done). You can view the case study page at `/work/cognet-case-study/` - it doesn't display on `/work` yet.

I'd welcome feedback on theming and content - this is a first pass!

To do: Add case studies to `/work` and the front page.

### CODE REVIEW

**Comment by AnneTee** [comment]
@chris et al this now includes:
- One case study (Cognet responsive redesign)
- Case studies on home page (I plan to make the image overlay color a different color in our color scheme for each one so they won't all be blue)
- Case studies on /work (same thing with the colors)

I could use feedback on:
- The case study design and content
- What we should do with the old work pages on /work - should we redo the cards to match the style of the case studies? 
- The style of the case studies on /work and home
- The headings on /work and home
- Any other language updates
- I mean really anything

**Comment by chrisarusso** [comment]
@AnneTee I pushed up my own branch rather than adding to yours at the moment but feel free to use whatever workflow works for you. I isolated my commits on my branch to help with feedback:https://github.com/chrisarusso/savaslabs.github.io/commits/717-update-portfolio

Please have a look at each commit and see if you agree.

Comments are:
- Tests are failing at the moment, I could use help with linking things we haven't blogged about yet
- Interested to hear you input on two quotes? Should we hold off on that? Can we do it in a better way?
- Have at some images and let me know what else you might want to change or need from me?

Thanks!

**Comment by AnneTee** [comment]
@chris I made some comments in your code but I'll answer your bullets here:
- I think we can just not link things that don't have a relevant tag
- I think two quotes is great, and having one right up front is awesome. Going to make one small styling adjustment (reducing the padding-top of the quote)
- Will do, and I think I'm good but I'll let you know if I have questions

**Comment by AnneTee** [comment]
Closing as this was merged elsewhere

**Pull request closed without merging**
