### PR TITLE
Issue #2600: Update Ro profile

### PR DESCRIPTION
**Pull request by lrowang**
**Status: Ready for merge!**

Hi @AnneTee -

This commit updates my profile description and adds the missing links to my professional accounts! If you could double check that all looks good and then merge that'd be much appreciated!

Note: the failing html tests is the my stackoverflow/cv link that just got created. Hopefully it will work within 24hrs!

### CODE REVIEW

**Review by AnneTee — CHANGES_REQUESTED** [review]
@lrowang Looking good! Just a couple things...

- The resume link still isn't working, so we won't be able to merge this until it's fixed since it won't deploy if tests fail. Hopefully it'll happen soon?
- I can't access your drupal.org profile unless I'm logged in - there may be a setting somewhere for setting your profile to public/private and you may want to set it to public.

🍭 🍬 🍨

**Comment by lrowang** [comment]
Thanks @AnneTee !

- The resume link is working and I re-ran the Travis ~build and the html tests passed - hooray!~ Just kidding, still not passing. Going to ask Stackoverflow.
- I think public/private setting is controlled by account status. I'm still "unconfirmed" since my account is so new. I submitted an "Request for `confirmed` user role" [issue](https://www.drupal.org/node/2841353) to the D.O. webmasters -- hopefully they'll grant it so that my profile can be viewed publicly. 

Do we wan to wait for D.O. or go ahead and merge these updates now that resume link is working?

**Comment by AnneTee** [comment]
@lrowang This just started working for me locally, woohoo! As long as the tests pass now (which they should) on Travis we can merge! 👍

**Review by AnneTee — APPROVED** [review]

**Comment by lrowang** [comment]
Yay! Tests passed! I'm going to merge!
🍭 😄 🍭

**Pull request merged**
