### PR TITLE
Job banner

### PR DESCRIPTION
**Pull request by AnneTee**
@kostajh @chrisarusso Let me know what you think :hibiscus:

### CODE REVIEW

**Comment by chrisarusso** [comment]
It's even louder :postal_horn: than the previous. Me gusta :tada:  There's something failing on Travis, though. Ha. Scratch that. It's a broken :sunny: :shower: s link because it's the day of the upgrade and rfay is in the middle of the lengthy upgrade.

**Comment by AnneTee** [comment]
Yeah the text is kind of huge which we could totally change. I think the orange is ok though. I've been wanting to get some orange on the site to pull in the logo more.

**Comment by chrisarusso** [comment]
retest this please

**Comment by chrisarusso** [comment]
Are you listening Travis?

**Pull request merged**
