### PR TITLE
Issue #3282: services pages

### PR DESCRIPTION
**Pull request by AnneTee**
@oksana-c This PR:

- Is based on my `refactor-tiles` branch, so I can rebase if that one gets merged first
- #3282: Builds the 4 service pages. These are created by markdown tiles in the `_services` directory and are output in the `service.html` layout. I added page-level styles for this page, mostly for the main section including the page copy and vertical image.
- #3211: Adds a new type of banner for the two regions specific to the Development page (performance optimizations and custom integrations). For now I'm using the same image for both - the custom integrations one needs to be added
- Adds region templates for related case studies and related blog posts. These work on the service pages and I'm hoping we can reuse them on tag pages.
- Makes some adjustments to the client quote styles
- Adds some classes so the service icons can be reused on the service pages since the hover styles differ from the icons on the home page
- Adds `services` front matter item to all case studies and some recent blog posts. I took a guess at these; you or Chris may want to refine them.

The responsive behavior here was tricky so please let me know if you have any suggestions for improvements! ☀️

### CODE REVIEW

**Comment by AnneTee** [comment]
@oksana-c I'm having a hell of a time getting the custom integrations image to look good at all screen sizes. I think removing the shadowing from the image (at least below ~1300 px screen width) would help, but for now i'm just not showing the image until 860px and then it looks a little funny up until 1300px. I'm not happy with this but I need to move on...let me know if you have any suggestions and sorry this one isn't resolved!

**Comment by oksana-c** [comment]
@AnneTee - let's insert it as a background image - and use similar technique for positioning it as I used for services page hero images. I can get on this in a bit.

**Comment by oksana-c** [comment]
@AnneTee - I added styles for the integrations banner. They are not as reusable as I would like them to be, because of the background-image used in the banner. We are unlikely to have a need for this style in the future and if we do, we'll standardize this. Please test this and merge if all looks good to you. Thanks

**Review by oksana-c — APPROVED** [review]

**Comment by AnneTee** [comment]
@oksana-c All looks good to me!

**Pull request merged**
