### PR TITLE
Issue #7440: update gulp and resolve NPM security vulnerabilities

### PR DESCRIPTION
**Pull request by AnneTee**
Fixes issue [#7440](https://pm.savaslabs.com/issues/7440)

## Summary of changes

1. Updates NPM packages to fix security issues
2. This includes updating gulp to gulp 4, which required major updates to gulp tasks. I made these updates and split the gulpfile up into smaller task files located in `_tasks` to make things more maintainable.
3. Added npm scripts to run gulp commands using the version of gulp in the project rather than the user's global gulp install
4. Updated the README to reflect this
5. Fixed some coding standards issues and optimized a few images

## To test

- [x] Run `npm install` and confirm you see a message saying `found 0 vulnerabilities` afterward
- [x] Run `npm run build` and confirm the site builds without error
- [x] Run `npm run serve:rebuild` and confirm the site rebuilds then then pops up in the browser

### Pull request reviewer

As the reviewer, I have verified the following:

- [x] I have tested the PR locally and/or in a staging environment

### CODE REVIEW

**Comment by chrisarusso** [comment]
Left feedback in regards to `npm install` on [#7440](https://pm.savaslabs.com/issues/7440)

I was able to build with `npm run build` - that seemed to work without errors

`npm run serve:rebuild` worked, but quickly failed with:

```
[debug] +  Step Complete: Starting the UI
[debug] -> Starting Step: Merge UI settings
[debug] Setting Option: urls - Map { "local": "http://localhost:3000", "external": "http://10.255.1.48:3000", "ui": "http://localhost:3001", "ui-external": "http://localhost:3001" }
[debug] +  Step Complete: Merge UI settings
[debug] -> Starting Step: Init user plugins
[debug] Setting Option: userPlugins - 
[debug] +  Step Complete: Init user plugins
[Browsersync] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://10.255.1.48:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ------------------------------------
[Browsersync] Serving files from: _site/
[Browsersync] Browser Connected: Chrome, version: 71.0.3578.98
[16:36:36] 'serve' errored after 3.48 s
[16:36:36] Error: no parsers registered for: "]a(r)"
    at parse (/Users/chris/web/savas-site/node_modules/snapdragon/lib/parser.js:473:15)
    at Parser.parse (/Users/chris/web/savas-site/node_modules/snapdragon/lib/parser.js:477:24)
    at Snapdragon.parse (/Users/chris/web/savas-site/node_modules/snapdragon/index.js:122:28)
    at Snapdragon.<anonymous> (/Users/chris/web/savas-site/node_modules/chokidar/node_modules/braces/lib/braces.js:40:45)
    at Braces.parse (/Users/chris/web/savas-site/node_modules/chokidar/node_modules/braces/lib/braces.js:66:26)
    at Braces.expand (/Users/chris/web/savas-site/node_modules/chokidar/node_modules/braces/lib/braces.js:87:18)
    at create (/Users/chris/web/savas-site/node_modules/chokidar/node_modules/braces/index.js:142:15)
    at memoize (/Users/chris/web/savas-site/node_modules/chokidar/node_modules/braces/index.js:298:13)
    at Function.braces.create (/Users/chris/web/savas-site/node_modules/chokidar/node_modules/braces/index.js:165:10)
    at Function.braces.expand (/Users/chris/web/savas-site/node_modules/chokidar/node_modules/braces/index.js:81:17)
    at getDirParts (/Users/chris/web/savas-site/node_modules/chokidar/index.js:435:31)
    at FSWatcher.<anonymous> (/Users/chris/web/savas-site/node_modules/chokidar/index.js:452:24)
    at /Users/chris/web/savas-site/node_modules/readdirp/readdirp.js:226:72
    at Array.filter (<anonymous>)
    at /Users/chris/web/savas-site/node_modules/readdirp/readdirp.js:226:12
    at /Users/chris/web/savas-site/node_modules/readdirp/readdirp.js:199:38
[16:36:36] 'serve:rebuild' errored after 1.73 min
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! savas-take-two@1.0.0 serve:rebuild: `gulp serve:rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the savas-take-two@1.0.0 serve:rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chris/.npm/_logs/2019-01-11T21_36_36_077Z-debug.log
```

That log filed ^ output is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve:rebuild' ]
2 info using npm@6.5.0
3 info using node@v10.10.0
4 verbose run-script [ 'preserve:rebuild', 'serve:rebuild', 'postserve:rebuild' ]
5 info lifecycle savas-take-two@1.0.0~preserve:rebuild: savas-take-two@1.0.0
6 info lifecycle savas-take-two@1.0.0~serve:rebuild: savas-take-two@1.0.0
7 verbose lifecycle savas-take-two@1.0.0~serve:rebuild: unsafe-perm in lifecycle true
8 verbose lifecycle savas-take-two@1.0.0~serve:rebuild: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/chris/web/savas-site/node_modules/.bin:/Users/chris/.yarn/bin:/Users/chris/.config/yarn/global/node_modules/.bin:/Users/chris/Library/Python/2.7/bin:/Users/chris/.rvm/gems/ruby-2.2.1/bin:/Users/chris/.rvm/gems/ruby-2.2.1@global/bin:/Users/chris/.rvm/rubies/ruby-2.2.1/bin:/usr/local/sbin:/Users/chris/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Users/chris/.rvm/bin:/Users/chris/.rvm/bin
9 verbose lifecycle savas-take-two@1.0.0~serve:rebuild: CWD: /Users/chris/web/savas-site
10 silly lifecycle savas-take-two@1.0.0~serve:rebuild: Args: [ '-c', 'gulp serve:rebuild' ]
11 silly lifecycle savas-take-two@1.0.0~serve:rebuild: Returned: code: 1  signal: null
12 info lifecycle savas-take-two@1.0.0~serve:rebuild: Failed to exec serve:rebuild script
13 verbose stack Error: savas-take-two@1.0.0 serve:rebuild: `gulp serve:rebuild`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid savas-take-two@1.0.0
15 verbose cwd /Users/chris/web/savas-site
16 verbose Darwin 15.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve:rebuild"
18 verbose node v10.10.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error savas-take-two@1.0.0 serve:rebuild: `gulp serve:rebuild`
22 error Exit status 1
23 error Failed at the savas-take-two@1.0.0 serve:rebuild script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by chrisarusso** [comment]
Also @AnneTee are the necessary updates incorporated for the `build.sh` file or the `.travis.yml` file?

**Comment by lrowang** [comment]
@AnneTee 

1. I ran `npm install` and I did not see the message `found 0 vulnerabilities`
2. I ran `npm run build` and it did not complete successfully
(Note I did run `npm -i -g npm` to update it in between step 1 and 2 just cause I was prompted.)

Here's my output.
https://gist.github.com/lrowang/123297347094b3240fa9ed0cacc56ed9

My versions
```
Ro@ro >> npm --version                                                 (feature/update-gulp) ~/s/savaslabs.github.io
6.5.0
Ro@ro >> node --version                                                (feature/update-gulp) ~/s/savaslabs.github.io
v6.9.1
Ro@ro >> sw_vers                                                       (feature/update-gulp) ~/s/savaslabs.github.io
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G4015
```

**Comment by dmurphy1** [comment]
@AnneTee - I ran `bundle update` and then re-ran those steps and the site is working for me locally now!

**Pull request merged**
