### PR TITLE
Blog pages

### PR DESCRIPTION
**Pull request by AnneTee**
@oksana-c This PR sets up the markup for the main blog page and subsequent paginated pages, blog posts, and tag pages. I haven't styled these pages or their elements, just got the markup set up.

The one thing missing here is the topics section on the main blog page. I've run into a wall here and would like to hold off on more work on this until other higher priority items are completed. The issue is that it may not be possible to create an associative array in Liquid and the workaround involves using two arrays, but that won't allow me to sort one array and affect the other. I'm sure we can solve this but I'd like to put it on hold for now.

Next I'll work on styling this stuff!

### CODE REVIEW

**Comment by AnneTee** [comment]
@oksana-c Update: I've styled the elements on the main blog page, including subsequent pages when you page through the posts. Feedback welcome!

**Comment by AnneTee** [comment]
@oksana-c I think this is at a good point for you to review. I've finished styling the main blog page and the blog post pages with the exception of the comments section. I'm going to do that in a separate PR so I can assign it to Kosta for testing since he has the comment server set up locally. I also haven't styled the tag pages yet. I want to move on to building markup, but I intend to finish the comments and the tag pages once i've finished with the markup.

Thanks!

**Review by oksana-c — APPROVED** [review]
@AnneTee : per our chat in Slack I added blog post pagination on mobile. Also added blog heading texture and rebased this branch. If recent change look good to you - let's merge. Great work on the blog pages! 👍  Thanks!

**Comment by AnneTee** [comment]
Perfect! 👍

**Pull request merged**
