### PR TITLE
Issue #3319: Add list of contrib modules

### PR DESCRIPTION
**Pull request by lrowang**
Redmine issue [3319](https://pm.savaslabs.com/issues/3319)

Hi @AnneTee -

This PR adds this [list](https://pm.savaslabs.com/issues/8#note-5) of SL contributions to `/results/open-source/`. I got it up locally and it's working, but need to double check the following with you (in order of importance):

**1. Modules with no commits, just "issues"**
For example, the list says "1 issue", and I'm guessing this is where we've filed an issue for this project but didn't make a commit. **Should I remove these from the list?** Currently I've put them down as `number_commits: 0`, but it renders like this `BigPipe (0)` (See Pic1). 
- BigPipe
- Feeds

**2. Modules with external "main project" links**
In both cases I put the DO links in keeping with format, but they are out-of-date compared to the "real project" page. So just wanted to see what you preferred here.
- Console
  - https://drupalconsole.com/
  - https://www.drupal.org/project/console
- Drush
  - https://github.com/drush-ops/drush
  - https://www.drupal.org/project/drush

**3. Modules I looked up commit numbers for**
These modules didn't have commit numbers in the list, so I looked them up and put in the below:
- Commerce Discount - 1 commit by Dan
- Mandrill Incoming - 1 commit by Kosta
- No Autocomplete - 2 commit by Dan
- Token Action Extras - 9 commit by Dan
- Views geojson drupal 8 - 33 collective commits

**4. Removed modules**
I took these out of the list b/c they are already prominently featured higher up on the page:
- Drush rebuild
- Tournament
- Salesforce Suite
- SubDrush
- Drush Code Deploy
- Drupal uP

Let me know what needs to be changed!

**Pic1**
sl-1

### CODE REVIEW

**Comment by AnneTee** [comment]
@lrowang Sweet!

1. You can remove the modules for which we haven't done any commits
2. Please use the current URL rather than the old do.org one

Everything else looks good - thanks!

**Comment by oksana-c** [comment]
@AnneTee - can we sort these modules by the amount of commits in descending order? (only for the `many others` section, not tiles)

**Comment by AnneTee** [comment]
@oksana-c Yes good call! I've sorted the items by # commits.

@lrowang I went ahead and made the changes from my last comment - this should be good to go once tests pass!

**Review by AnneTee — APPROVED** [review]

**Comment by lrowang** [comment]
👍  thanks guys!

**Pull request merged**
