### PR TITLE
Issue #3143: blog tile component and region

### PR DESCRIPTION
**Pull request by AnneTee**
@oksana-c 

**Note**: this branch was based on the branch for #238, so this will need to be rebased after that branch is merged.

This PR covers 2 main issues:

## Issue 3150: blog tiles
- This PR adds styles and markup for blog tiles and the blog tile region, and adds this region to the home page. Since the styles for the individual tiles depend heavily on the region as a whole due to the flexbox layout, I removed single tiles from the components section of the styleguide and am just displaying the region on the Regions tab (same for case study tiles).
- We'll be able to adapt this region for team member pages using the same styles.
- One shortcoming of this is that to allow the image to maintain the correct dimensions without skewing the image itself, I had to set it as a background cover image. This means we can't use the `jekyll-picture-tag` plugin to automatically create properly sized images for us. We could do this manually eventually to ensure we're not loading a large image for such a small display.

I also made two changes to your design:
1. For the blog card title section: because the light teal color is a 90% transparent version of the regular teal color, text on top of it will not pass WCAG contrast tests (I tried dark teal and grey). We can either change the light-teal color to a 100% opaque light teal hex code, or we can go with the eggshell background as I've done here.
2. I adjusted the spacing of the "view all posts" link to visually pair it with the blog tiles

## Issue 3149: case study tiles
- This PR adds styles and markup for case study tiles and the case study tile region, and adds this region to the home page.

## Additional work in this PR

I refactored and added some code while doing this work. A summary:

- Adjust the gulp watch task to keep the browser from reloading twice
- Adjust some link styles to ensure they match the mockups and that the hover styles don't affect the layout
- Abstract some typography styles into mixins (e.g. heading underline and paragraph font sizes)
- Increase the max width of the site to 1440px since that's the width the mockups are based on
- Set up some wrapper classes to help us with page layout

I know I'm getting a bit ahead of myself with the page-level work, but I wanted to work out some of the layout kinks before we both start working together on adding components/pages so that we'll have the same classes and mixins to work with.

Please let me know if you have any feedback! P.S. I've tested this at multiple screen sizes in Chrome and FF but nothing else yet. 🍰 🍪 🍨

### CODE REVIEW

**Comment by oksana-c** [comment]
Hi @AnneTee , great work on both blog and case study tiles! I tested on different screen sizes and responsive styles look great. I have a few requests which I'll list below.

1. Let's go with the light teal color for the blog tiles. It is in fact 95% transparency on the mockup, so it is lighter. Just tried it in the WCAG contrast tool and getting all passes. Here's the HEX code for it `#f3f6f7`. Pasted screenshot in Slack for reference.

2. Spacing of the "View All Posts" works for me if you find it more intuitive. The only thing that I'd like to suggest is to remove the `max-width` value for the blog tiles region. My plan is to have certain sections stretch edge-to-edge, which gives a stronger impact to the design concept overall.

3. Case Study tiles look beautiful! I suggest that we make them full-width, same as the "blog tiles" region on all screen sizes for stronger impact and more modern look. Tried removing max-width locally and the style that you created hold beautifully full-width. Also, let's give a bit more padding (top and bottom) to the tile that holds "Results" heading and CTA button on mobile.

We can follow up on some of these things in Slack tomorrow. :wave:

**Comment by AnneTee** [comment]
Thanks @oksana-c! Here's a to-do list for this PR based on your comments above and in slack:

- [x] Change $light-teal to hex code rather than using `transparentize` function and set blog tile backgrounds to $light-teal
- [x] Remove max-width on tiles regions
- [x] Add top and bottom padding to case study title tile
- [x] Remove max width from core values list, but maintain max width on the actual content within that region. Border-bottom should be full screen width
- [x] Update spacing on "Move work forward" section
- [x] Fix blog tile hover height issue on mobile

I'll be working on this this afternoon!

**Comment by AnneTee** [comment]
@oksana-c I've made all of the updates in the list above! Please let me know if there's anything else. If this is ready, we could merge this PR and close #238 since the commits from #238 are included here. ☀️

**Review by oksana-c — APPROVED** [review]
@AnneTee - thank you for implementing those changes. Everything looks great! Leaving to you to merge.

**Pull request merged**
