### PR TITLE
[WIP] SAV-53: Add linkedin links and refactor team social/professional media links

### PR DESCRIPTION
**Pull request by AnneTee**
@kostajh I think the tables on the team pages were a little unnecessary given how little information they were providing. I swapped them out for a row of links similar to the footer. What to do you think? Too much fuschia?

### CODE REVIEW

**Comment by kostajh** [comment]
One can never have too much fuschia, but I'm undecided about the re-organization. On the other hand I agree that the table seemed a little much. @dmurphy1 and @timstallmann what do you think?

**Comment by dmurphy1** [comment]
Yeah, I'm not sure. I think the username in the table isn't all that important (and is redundant in many cases) but fuchsia icons might be a little much for me @AnneTee, @kostajh, @timstallmann. But my feelings are that strong about it.

**Comment by AnneTee** [comment]
@dmurphy1 totally agree. I kept them fuschia because it's the link color and it transitions nicely into the orange on hover/focus. But, headings AND links all being fuschia is becoming a bit much. I think we should probably rethink this and possibly make headings a different color. We could make headings dark blue like the text, or add one more color that contrasts with white. I'll play around with this tomorrow, and welcome input/suggestions/solutions!

**Comment by kostajh** [comment]
@AnneTee I do think variation in the header colors and styles would be useful. Also, for the icons, they're not all the same size and not vertically aligned which makes it harder to judge this.

screen

One thing I don't particularly like about just using icons is that it requires the user to know ahead of time what those mean. Most people would recognize the twitter icon & linkedin but the others are not as well known.

All this being said, I do think this is an improvement over the table presentation. One idea we could explore is better utilizing the space at the top where we have name, image, job title: rearranging those so they fit in one row instead of three, and incorporating the social icons somewhere as well.

**Comment by AnneTee** [comment]
@kostajh @dmurphy1 thanks for all the feedback! 

I just pushed another option - inline icons with text links. The icons are still slightly different sizes and the stupid LinkedIn one sits below the rest, but they're small and spaced out enough that I think it's still pleasing to the eye. But that's just my opinion so please let me know what y'all think (you too @timstallmann)

**Comment by kostajh** [comment]
@AnneTee +1 I like this approach. IMO it's still too monochromatic but we could deal with that in another PR. I'd also like to figure out a different approach for photo + job title + name but again, that can be in another PR.

**Pull request merged**
